### ISSUE TITLE
Extension is not working on latest GMS2

### ISSUE THREAD

**Issue by lcnvdl** [time-killer-games/libdlgmod#1]
Hello!

I was using this library for my game, but since I've updated GMS2 to the latest version, the library is not showing any dialog at all.

In the Output, I get the next error:
```
LoadLibraryW Y:\yar_guard_462FB3B6_VM\libdlgmod.dll failed with error code 126
```

I'm using Windows 10. The game is for Windows.

IDE version: 2.3.3.570
Runtime: 2.3.3.434

Thank you very much

**Comment by lcnvdl** [comment]
I'm using the version published at the Yoyo Games Store.

**Comment by time-killer-games** [comment]
Try downloading the 64-bit from here:
https://github.com/time-killer-games/libdlgmod/releases/tag/v1.0.0.0

Either that, or try switching to the 32-bit runtime.

Either should work if the issue is what I suspect.

**Comment by lcnvdl** [comment]
Wow, thanks for your fast answer!

I've replaced the dll with the one you've published 6 days ago , and it is working again!

Thank you very much

**Comment by time-killer-games** [comment]
No problem! Thank you for reaching out~
