### ISSUE TITLE
GameMaker2 running in full screen is minimized while selecting file

### ISSUE THREAD

**Issue by proserveit** [time-killer-games/libdlgmod#1]
Hello,

I have found that the libdlgmod when running in Windows and running GameMaker2, the GameMaker 2 window is minimized when in full screen.  Is there a work around for this or a way it can be fixed in the GML or C++ extension code?  Thank you

**Comment by time-killer-games** [comment]
What you are looking for is borderless fullscreen, which will require another extension.

I don't have access to my computers atm but it should just be a matter of using borderless fullscreen with my "BorderToggler" asset from here:

https://samuel-venable.itch.io/gamemaker-extension-collection

Create Event:

```
ww = window_get_width();
wh = window_get_height();
```

To go fullscreen, simply do:

```
ww = window_get_width();
wh = window_get_height();
window_set_showborder(false);
window_set_rectangle(0, 0, display_get_width(), display_get_height());
```

Restore to windoqed mode:

```
window_set_showborder(true);
window_set_rectangle(0, 0, ww, wh);
```

Let me know if that works for you.

**Comment by proserveit** [comment]
Hi there,  ​   Thank you for your response, I do greatly appreciate it and thought I replied but found this in my tickets.  ​   We ended up just using the default functions rather than external extensions and tools and it is all working properly.  By memory, it didn't quite work as expected, although I may have missed something, but thank you for your input.      Thank you       Regards Michael   
                           
                            On
                            Tue, 21 Feb at 11:35 PM
                            ,  time-killer-games/libdlgmod ***@***.***>  wrote:
                             
 What you are looking for is borderless fullscreen, which will require another extension. 
 I don't have access to my computers atm but it should just be a matter of using borderless fullscreen with my "BorderToggler" asset from here: 
 https://samuel-venable.itch.io/gamemaker-extension-collection 
 Create Event: 
 ww = window_get_width();
wh = window_get_height();
 
 To go fullscreen, simply do: 
 ww = window_get_width();
wh = window_get_height();
window_set_showborder(false);
window_set_rectangle(0, 0, display_get_width(), display_get_height());
 
 Restore to windoqed mode: 
 window_set_showborder(true);
window_set_rectangle(0, 0, ww, wh);
 
 Let me know if that works for you.

**Comment by time-killer-games** [comment]
> Hi there, ​ Thank you for your response, I do greatly appreciate it and thought I replied but found this in my tickets. ​ We ended up just using the default functions rather than external extensions and tools and it is all working properly.  By memory, it didn't quite work as expected, although I may have missed something, but thank you for your input. Thank you Regards Michael On Tue, 21 Feb at 11:35 PM , time-killer-games/libdlgmod ***@***.***> wrote: What you are looking for is borderless fullscreen, which will require another extension. I don't have access to my computers atm but it should just be a matter of using borderless fullscreen with my "BorderToggler" asset from here: https://samuel-venable.itch.io/gamemaker-extension-collection Create Event: ww = window_get_width(); wh = window_get_height(); To go fullscreen, simply do: ww = window_get_width(); wh = window_get_height(); window_set_showborder(false); window_set_rectangle(0, 0, display_get_width(), display_get_height()); Restore to windoqed mode: window_set_showborder(true); window_set_rectangle(0, 0, ww, wh); Let me know if that works for you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

yeah at this point the windows platform of this is extension is no longer actively supported since you can just use the built in functions to get borderless mode, as for macOS and Linux you can still use this extension so it can work on those platforms as well if you need borderless mode to not be Windows-only.

**Comment by time-killer-games** [comment]
I am closing this issue now because I believe using the built-in borderless mode GameMaker now provides should be all you need to resolve this. If not, please re-open this issue and let me know a clear description of why that solution won't be working for you.
