### ISSUE TITLE
get_string_async() returns undefined

### ISSUE THREAD

**Issue by Grix** [time-killer-games/libdlgmod#4]
Hi, unfortunately I'm here again with another bug I found while testing... 😅
get_string_async() no longer works. The resulting value in the returned dictionary is "undefined", no matter what text you enter. 

This seems to be the culprit: https://github.com/time-killer-games/libdlgmod/commit/e7ffd6113785548bada612d4982348d3b07ea81d
When implementing the cancel feature, the dictionary key "result" was accidentally replaced with "value", as it is for f.ex. get_integer. I don't know why Yoyogames made the spec different for these dialogs in this way, but to be compatible with the native get_string_async you have to change back to "result".

**Comment by time-killer-games** [comment]
The asset has been updated, note I still only compiled the macOS binary to support the latest macOS, but other than that, you should be all set! All other assets of mine which depend on Dialog Module have also been updated. Grab the update on itch,io:

https://samuel-venable.itch.io/gamemaker-extension-collection

**Comment by Grix** [comment]
> Don't hesitate to let me know if you run into more issues. :D

Thanks, will do👍
